<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class SectorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $sectors = [
            ['SBI' => '011', 'Omschrijving' => 'Teelt van eenjarige gewassen'],
            ['SBI' => '012', 'Omschrijving' => 'Teelt van meerjarige gewassen'],
            ['SBI' => '013', 'Omschrijving' => 'Teelt van sierplanten en –bomen en bloembollen'],
            ['SBI' => '014', 'Omschrijving' => 'Fokken en houden van dieren'],
            ['SBI' => '015', 'Omschrijving' => 'Akker- en/of tuinbouw in combinatie met het fokken en houden van dieren'],
            ['SBI' => '016', 'Omschrijving' => 'Dienstverlening voor de landbouw; behandeling van gewassen na de oogst'],
            ['SBI' => '017', 'Omschrijving' => 'Jacht'],
            ['SBI' => '021', 'Omschrijving' => 'Bosbouw'],
            ['SBI' => '022', 'Omschrijving' => 'Exploitatie van bossen'],
            ['SBI' => '024', 'Omschrijving' => 'Dienstverlening voor de bosbouw'],
            ['SBI' => '031', 'Omschrijving' => 'Visserij'],
            ['SBI' => '032', 'Omschrijving' => 'Kweken van vis en schaaldieren'],
            ['SBI' => '061', 'Omschrijving' => 'Winning van aardolie'],
            ['SBI' => '062', 'Omschrijving' => 'Winning van aardgas'],
            ['SBI' => '081', 'Omschrijving' => 'Winning van zand grind en klei'],
            ['SBI' => '089', 'Omschrijving' => 'Winning van overige delfstoffen'],
            ['SBI' => '091', 'Omschrijving' => 'Dienstverlening voor de winning van aardolie- en aardgas'],
            ['SBI' => '099', 'Omschrijving' => 'Dienstverlening voor de winning van delfstoffen geen olie en gas'],
            ['SBI' => '101', 'Omschrijving' => 'Slachterijen en vleesverwerking'],
            ['SBI' => '102', 'Omschrijving' => 'Visverwerking'],
            ['SBI' => '103', 'Omschrijving' => 'Verwerking van aardappels groente en fruit'],
            ['SBI' => '104', 'Omschrijving' => 'Vervaardiging van plantaardige en dierlijke oliën en vetten'],
            ['SBI' => '105', 'Omschrijving' => 'Vervaardiging van zuivelproducten'],
            ['SBI' => '106', 'Omschrijving' => 'Vervaardiging van meel'],
            ['SBI' => '107', 'Omschrijving' => 'Vervaardiging van brood vers banketbakkerswerk en deegwaren'],
            ['SBI' => '108', 'Omschrijving' => 'Vervaardiging van overige voedingsmiddelen'],
            ['SBI' => '109', 'Omschrijving' => 'Vervaardiging van diervoeders'],
            ['SBI' => '110', 'Omschrijving' => 'Vervaardiging van dranken'],
            ['SBI' => '120', 'Omschrijving' => 'Vervaardiging van tabaksproducten'],
            ['SBI' => '131', 'Omschrijving' => 'Bewerken en spinnen van textielvezels'],
            ['SBI' => '132', 'Omschrijving' => 'Weven van textiel'],
            ['SBI' => '133', 'Omschrijving' => 'Textielveredeling'],
            ['SBI' => '139', 'Omschrijving' => 'Vervaardiging van overige textielproducten'],
            ['SBI' => '141', 'Omschrijving' => 'Vervaardiging van kleding geen bontkleding'],
            ['SBI' => '142', 'Omschrijving' => 'Vervaardiging van artikelen van bont'],
            ['SBI' => '143', 'Omschrijving' => 'Vervaardiging van gebreide en gehaakte kleding'],
            ['SBI' => '151', 'Omschrijving' => 'Looien en bewerken van leer; vervaardiging van koffers tassen zadel- en tuigmakerswerk; bereiden en verven van bont'],
            ['SBI' => '152', 'Omschrijving' => 'Vervaardiging van schoenen'],
            ['SBI' => '161', 'Omschrijving' => 'Primaire houtbewerking en verduurzamen van hout'],
            ['SBI' => '162', 'Omschrijving' => 'Vervaardiging van artikelen van hout kurk riet en vlechtwerk geen meubels'],
            ['SBI' => '171', 'Omschrijving' => 'Vervaardiging van papierpulp papier en karton'],
            ['SBI' => '172', 'Omschrijving' => 'Vervaardiging van papier- en kartonwaren'],
            ['SBI' => '181', 'Omschrijving' => 'Drukkerijen en dienstverlening voor drukkerijen'],
            ['SBI' => '182', 'Omschrijving' => 'Reproductie van opgenomen media'],
            ['SBI' => '191', 'Omschrijving' => 'Vervaardiging van cokesovenproducten'],
            ['SBI' => '192', 'Omschrijving' => 'Aardolieverwerking'],
            ['SBI' => '201', 'Omschrijving' => 'Vervaardiging van chemische basisproducten kunstmeststoffen en stikstofverbindingen en van kunststof en synthetische rubber in primaire vorm'],
            ['SBI' => '202', 'Omschrijving' => 'Vervaardiging van verdelgingsmiddelen en overige landbouwchemicaliën'],
            ['SBI' => '203', 'Omschrijving' => 'Vervaardiging van verf vernis e.d. drukinkt en mastiek'],
            ['SBI' => '204', 'Omschrijving' => 'Vervaardiging van zeep wasmiddelen poets- en reinigingsmiddelen parfums en cosmetica'],
            ['SBI' => '205', 'Omschrijving' => 'Vervaardiging van overige chemische producten'],
            ['SBI' => '206', 'Omschrijving' => 'Vervaardiging van synthetische en kunstmatige vezels'],
            ['SBI' => '211', 'Omschrijving' => 'Vervaardiging van farmaceutische grondstoffen'],
            ['SBI' => '212', 'Omschrijving' => 'Vervaardiging van farmaceutische producten geen grondstoffen'],
            ['SBI' => '221', 'Omschrijving' => 'Vervaardiging van producten van rubber'],
            ['SBI' => '222', 'Omschrijving' => 'Vervaardiging van producten van kunststof'],
            ['SBI' => '231', 'Omschrijving' => 'Vervaardiging van glas en glaswerk'],
            ['SBI' => '232', 'Omschrijving' => 'Vervaardiging van vuurvaste keramische producten'],
            ['SBI' => '233', 'Omschrijving' => 'Vervaardiging van producten van klei voor de bouw'],
            ['SBI' => '234', 'Omschrijving' => 'Vervaardiging van overige keramische producten'],
            ['SBI' => '235', 'Omschrijving' => 'Vervaardiging van cement kalk en gips'],
            ['SBI' => '236', 'Omschrijving' => 'Vervaardiging van producten van beton gips en cement'],
            ['SBI' => '237', 'Omschrijving' => 'Natuursteenbewerking'],
            ['SBI' => '239', 'Omschrijving' => 'Vervaardiging van overige niet-metaalhoudende minerale producten'],
            ['SBI' => '241', 'Omschrijving' => 'Vervaardiging van ijzer en staal en van ferrolegeringen'],
            ['SBI' => '242', 'Omschrijving' => 'Vervaardiging van stalen buizen pijpen holle profielen en fittings daarvoor'],
            ['SBI' => '243', 'Omschrijving' => 'Overige eerste verwerking van staal'],
            ['SBI' => '244', 'Omschrijving' => 'Vervaardiging van edelmetalen en overige non-ferrometalen'],
            ['SBI' => '245', 'Omschrijving' => 'Gieten van metalen'],
            ['SBI' => '251', 'Omschrijving' => 'Vervaardiging van metalen producten voor de bouw'],
            ['SBI' => '252', 'Omschrijving' => 'Vervaardiging van reservoirs van metaal en van ketels en radiatoren voor centrale verwarming'],
            ['SBI' => '253', 'Omschrijving' => 'Vervaardiging van stoomketels geen ketels voor centrale verwarming'],
            ['SBI' => '254', 'Omschrijving' => 'Vervaardiging van wapens en munitie'],
            ['SBI' => '255', 'Omschrijving' => 'Smeden persen stampen en profielwalsen van metaal; poedermetallurgie'],
            ['SBI' => '256', 'Omschrijving' => 'Oppervlaktebehandeling en bekleding van metaal; algemene metaalbewerking'],
            ['SBI' => '257', 'Omschrijving' => 'Vervaardiging van scharen messen en bestek hang- en sluitwerk en gereedschap'],
            ['SBI' => '259', 'Omschrijving' => 'Vervaardiging van overige producten van metaal'],
            ['SBI' => '261', 'Omschrijving' => 'Vervaardiging van elektronische componenten en printplaten'],
            ['SBI' => '262', 'Omschrijving' => 'Vervaardiging van computers en randapparatuur'],
            ['SBI' => '263', 'Omschrijving' => 'Vervaardiging van communicatieapparatuur'],
            ['SBI' => '264', 'Omschrijving' => 'Vervaardiging van consumentenelektronica'],
            ['SBI' => '265', 'Omschrijving' => 'Vervaardiging van meet- regel- navigatie- en controleapparatuur en van uurwerken'],
            ['SBI' => '266', 'Omschrijving' => 'Vervaardiging van bestralingsapparatuur en van elektromedische en elektrotherapeutische apparatuur'],
            ['SBI' => '267', 'Omschrijving' => 'Vervaardiging van optische instrumenten en apparatuur'],
            ['SBI' => '268', 'Omschrijving' => 'Vervaardiging van informatiedragers'],
            ['SBI' => '271', 'Omschrijving' => 'Vervaardiging van elektromotoren elektrische generatoren en transformatoren en van schakel- en verdeelinrichtingen'],
            ['SBI' => '272', 'Omschrijving' => 'Vervaardiging van batterijen en accumulatoren'],
            ['SBI' => '273', 'Omschrijving' => 'Vervaardiging van elektrische en elektronische kabels en van schakelaars stekkers stopcontacten e.d.'],
            ['SBI' => '274', 'Omschrijving' => 'Vervaardiging van elektrische lampen en verlichtingsapparaten'],
            ['SBI' => '275', 'Omschrijving' => 'Vervaardiging van huishoudapparaten'],
            ['SBI' => '279', 'Omschrijving' => 'Vervaardiging van overige elektrische apparatuur'],
            ['SBI' => '281', 'Omschrijving' => 'Vervaardiging van motoren turbines pompen compressoren appendages en drijfwerkelementen'],
            ['SBI' => '282', 'Omschrijving' => 'Vervaardiging van overige machines en apparaten voor algemeen gebruik'],
            ['SBI' => '283', 'Omschrijving' => 'Vervaardiging van machines en werktuigen voor de land- en bosbouw'],
            ['SBI' => '284', 'Omschrijving' => 'Vervaardiging van gereedschapswerktuigen'],
            ['SBI' => '289', 'Omschrijving' => 'Vervaardiging van overige machines apparaten en werktuigen voor specifieke doeleinden'],
            ['SBI' => '291', 'Omschrijving' => 'Vervaardiging van auto\s'],
            ['SBI' => '292', 'Omschrijving' => 'Carrosseriebouw; vervaardiging van aanhangwagens en opleggers'],
            ['SBI' => '293', 'Omschrijving' => 'Vervaardiging van onderdelen en toebehoren voor auto\s'],
            ['SBI' => '301', 'Omschrijving' => 'Scheepsbouw'],
            ['SBI' => '302', 'Omschrijving' => 'Vervaardiging van rollend spoor- en tramwegmaterieel'],
            ['SBI' => '303', 'Omschrijving' => 'Vervaardiging van vliegtuigen en onderdelen daarvoor'],
            ['SBI' => '304', 'Omschrijving' => 'Vervaardiging van militaire gevechtsvoertuigen'],
            ['SBI' => '309', 'Omschrijving' => 'Vervaardiging van transportmiddelen rest'],
            ['SBI' => '310', 'Omschrijving' => 'Vervaardiging van meubels'],
            ['SBI' => '321', 'Omschrijving' => 'Slaan van munten; bewerken van edelstenen en vervaardiging van sieraden'],
            ['SBI' => '322', 'Omschrijving' => 'Vervaardiging van muziekinstrumenten'],
            ['SBI' => '323', 'Omschrijving' => 'Vervaardiging van sportartikelen'],
            ['SBI' => '324', 'Omschrijving' => 'Vervaardiging van spellen en speelgoed'],
            ['SBI' => '325', 'Omschrijving' => 'Vervaardiging van medische instrumenten en hulpmiddelen'],
            ['SBI' => '329', 'Omschrijving' => 'Vervaardiging van overige goederen'],
            ['SBI' => '331', 'Omschrijving' => 'Reparatie van producten van metaal machines en apparatuur'],
            ['SBI' => '332', 'Omschrijving' => 'Installatie van industriële machines en apparatuur'],
            ['SBI' => '351', 'Omschrijving' => 'Productie van elektriciteit transmissie en distributie van elektriciteit en aardgas'],
            ['SBI' => '352', 'Omschrijving' => 'Productie van gas'],
            ['SBI' => '353', 'Omschrijving' => 'Productie en distributie van stoom warm water en gekoelde lucht'],
            ['SBI' => '360', 'Omschrijving' => 'Winning en distributie van water'],
            ['SBI' => '370', 'Omschrijving' => 'Afvalwaterinzameling en -behandeling'],
            ['SBI' => '381', 'Omschrijving' => 'Inzameling van afval'],
            ['SBI' => '382', 'Omschrijving' => 'Behandeling van afval'],
            ['SBI' => '383', 'Omschrijving' => 'Voorbereiding tot recycling'],
            ['SBI' => '390', 'Omschrijving' => 'Sanering en overig afvalbeheer'],
            ['SBI' => '411', 'Omschrijving' => 'Projectontwikkeling'],
            ['SBI' => '412', 'Omschrijving' => 'Algemene burgerlijke en utiliteitsbouw'],
            ['SBI' => '421', 'Omschrijving' => 'Bouw van wegen en spoorwegen'],
            ['SBI' => '422', 'Omschrijving' => 'Bouw van leidingen telecommunicatie- en elektriciteitsleidingen'],
            ['SBI' => '429', 'Omschrijving' => 'Bouw van overige civieltechnische werken'],
            ['SBI' => '431', 'Omschrijving' => 'Slopen van bouwwerken; voorbereiding van bouwterreinen'],
            ['SBI' => '432', 'Omschrijving' => 'Installatie van bouwbeslag warm water verwarming en airconditioning en elektrische installaties'],
            ['SBI' => '433', 'Omschrijving' => 'Afwerking van gebouwen'],
            ['SBI' => '439', 'Omschrijving' => 'Gespecialiseerde werkzaamheden in de bouw'],
            ['SBI' => '451', 'Omschrijving' => 'Handel in en reparatie van auto\s'],
            ['SBI' => '452', 'Omschrijving' => 'Reparatie en onderhoud van auto\s geen reparatie van carrosserieën'],
            ['SBI' => '453', 'Omschrijving' => 'Handel in en reparatie van auto-onderdelen en -accessoires'],
            ['SBI' => '454', 'Omschrijving' => 'Handel in en reparatie van motorfietsen en onderdelen daarvan'],
            ['SBI' => '461', 'Omschrijving' => 'Commissieveilingen en groothandel geen auto\s en motorfietsen'],
            ['SBI' => '462', 'Omschrijving' => 'Groothandel in landbouwproducten levend vee grondstoffen en halffabrikaten'],
            ['SBI' => '463', 'Omschrijving' => 'Groothandel in voedingsmiddelen dranken en tabak'],
            ['SBI' => '464', 'Omschrijving' => 'Groothandel in consumentenartikelen geen voedingsmiddelen dranken en tabak'],
            ['SBI' => '465', 'Omschrijving' => 'Groothandel in informatie- en communicatietechnologie'],
            ['SBI' => '466', 'Omschrijving' => 'Groothandel in machines apparaten en toebehoren voor de industrie'],
            ['SBI' => '467', 'Omschrijving' => 'Groothandel in brandstoffen ertsen metalen en chemische producten'],
            ['SBI' => '469', 'Omschrijving' => 'Gespecialiseerde groothandel in overige goederen rest'],
            ['SBI' => '471', 'Omschrijving' => 'Winkels in non-food artikelen'],
            ['SBI' => '472', 'Omschrijving' => 'Winkels in voedingsmiddelen dranken en tabak'],
            ['SBI' => '473', 'Omschrijving' => 'Tankstations'],
            ['SBI' => '474', 'Omschrijving' => 'Winkels in informatie- en communicatietechnologie'],
            ['SBI' => '475', 'Omschrijving' => 'Winkels in overige consumentenartikelen rest'],
            ['SBI' => '476', 'Omschrijving' => 'Markthandel in non-food artikelen'],
            ['SBI' => '477', 'Omschrijving' => 'Markthandel in voedingsmiddelen dranken en tabak'],
            ['SBI' => '478', 'Omschrijving' => 'Winkels in consumentenartikelen via internet'],
            ['SBI' => '479', 'Omschrijving' => 'Markthandel in consumentenartikelen'],
            ['SBI' => '491', 'Omschrijving' => 'Personenvervoer per spoor'],
            ['SBI' => '492', 'Omschrijving' => 'Vervoer per trein over lange afstand en overige passagiersvervoer per spoor'],
            ['SBI' => '493', 'Omschrijving' => 'Goederenvervoer per spoor'],
            ['SBI' => '494', 'Omschrijving' => 'Vervoer per bus'],
            ['SBI' => '495', 'Omschrijving' => 'Overig personenvervoer over de weg'],
            ['SBI' => '496', 'Omschrijving' => 'Goederenvervoer over de weg'],
            ['SBI' => '497', 'Omschrijving' => 'Taxivervoer'],
            ['SBI' => '501', 'Omschrijving' => 'Passagiersvaart'],
            ['SBI' => '502', 'Omschrijving' => 'Vervoer over zee en kustvaart'],
            ['SBI' => '503', 'Omschrijving' => 'Binnenvaart'],
            ['SBI' => '504', 'Omschrijving' => 'Goederenvervoer over water'],
            ['SBI' => '511', 'Omschrijving' => 'Luchtvaart'],
            ['SBI' => '512', 'Omschrijving' => 'Luchtvracht'],
            ['SBI' => '521', 'Omschrijving' => 'Opslag'],
            ['SBI' => '522', 'Omschrijving' => 'Dienstverlening voor vervoer over land'],
            ['SBI' => '523', 'Omschrijving' => 'Dienstverlening voor vervoer over water'],
            ['SBI' => '524', 'Omschrijving' => 'Dienstverlening voor vervoer door de lucht'],
            ['SBI' => '531', 'Omschrijving' => 'Postverzorging door universele dienstverlener'],
            ['SBI' => '532', 'Omschrijving' => 'Koeriers'],
            ['SBI' => '551', 'Omschrijving' => 'Hotels pensions en conferentieoorden'],
            ['SBI' => '552', 'Omschrijving' => 'Jeugdherbergen recreatiecentra en vakantiebungalows'],
            ['SBI' => '553', 'Omschrijving' => 'Kampeerterreinen'],
            ['SBI' => '559', 'Omschrijving' => 'Overige logiesverstrekking'],
            ['SBI' => '561', 'Omschrijving' => 'Restaurants'],
            ['SBI' => '562', 'Omschrijving' => 'Catering en overige maaltijdverzorging'],
            ['SBI' => '563', 'Omschrijving' => 'Cafés en bars'],
            ['SBI' => '581', 'Omschrijving' => 'Uitgeverijen'],
            ['SBI' => '582', 'Omschrijving' => 'Vervaardiging van computersoftware'],
            ['SBI' => '591', 'Omschrijving' => 'Filmproductie'],
            ['SBI' => '592', 'Omschrijving' => 'Geluidsopnamestudio\s en uitgeverijen van muziekwerken'],
            ['SBI' => '601', 'Omschrijving' => 'Radio-omroep'],
            ['SBI' => '602', 'Omschrijving' => 'Televisie-omroep'],
            ['SBI' => '611', 'Omschrijving' => 'Diensten in verband met de telecommunicatie'],
            ['SBI' => '612', 'Omschrijving' => 'Telecommunicatiediensten'],
            ['SBI' => '613', 'Omschrijving' => 'Telecombedrijven'],
            ['SBI' => '619', 'Omschrijving' => 'Telecommunicatie'],
            ['SBI' => '621', 'Omschrijving' => 'Praktijken van huisartsen en verloskundigen'],
            ['SBI' => '622', 'Omschrijving' => 'Tandartsen'],
            ['SBI' => '623', 'Omschrijving' => 'Alternatieve geneeswijzen'],
            ['SBI' => '624', 'Omschrijving' => 'Paramedische praktijken en alternatieve genezers'],
            ['SBI' => '631', 'Omschrijving' => 'Dataverwerking webhosting en aanverwante activiteiten'],
            ['SBI' => '639', 'Omschrijving' => 'Overige informatievoorziening'],
            ['SBI' => '641', 'Omschrijving' => 'Monetaire instellingen'],
            ['SBI' => '642', 'Omschrijving' => 'Beleggingsinstellingen en vennootschappen'],
            ['SBI' => '643', 'Omschrijving' => 'Beleggingsinstellingen en beheermaatschappijen'],
            ['SBI' => '649', 'Omschrijving' => 'Overige kredietverstrekking'],
            ['SBI' => '651', 'Omschrijving' => 'Verzekeringen'],
            ['SBI' => '652', 'Omschrijving' => 'Herverzekeringen'],
            ['SBI' => '653', 'Omschrijving' => 'Pensioenfondsen'],
            ['SBI' => '661', 'Omschrijving' => 'Diensten voor de financiële bemiddeling'],
            ['SBI' => '662', 'Omschrijving' => 'Diensten in verband met verzekeringen en pensioenfondsen; schade-experts en experts in schadebeperking'],
            ['SBI' => '663', 'Omschrijving' => 'Beheer van pensioenfondsen'],
            ['SBI' => '681', 'Omschrijving' => 'Verhuur van onroerend goed'],
            ['SBI' => '682', 'Omschrijving' => 'Verhuur van woonruimte'],
            ['SBI' => '683', 'Omschrijving' => 'Makelaarskantoren in onroerend goed'],
            ['SBI' => '691', 'Omschrijving' => 'Rechtskundige diensten'],
            ['SBI' => '692', 'Omschrijving' => 'Belastingadvies en accountantskantoren'],
            ['SBI' => '701', 'Omschrijving' => 'Holdingbedrijven'],
            ['SBI' => '702', 'Omschrijving' => 'Adviesbureaus voor bedrijfsvoering and public relations'],
            ['SBI' => '711', 'Omschrijving' => 'Architecten- en ingenieursbureaus; technische onderzoek en adviesbureaus'],
            ['SBI' => '712', 'Omschrijving' => 'Ingenieursbureaus'],
            ['SBI' => '721', 'Omschrijving' => 'Onderzoek en ontwikkeling op het gebied van de natuurwetenschappen en techniek'],
            ['SBI' => '722', 'Omschrijving' => 'Onderzoek en ontwikkeling op het gebied van de maatschappelijke en geesteswetenschappen'],
            ['SBI' => '731', 'Omschrijving' => 'Reclamebureaus en markt- en opinieonderzoekbureaus'],
            ['SBI' => '732', 'Omschrijving' => 'Markt- en opinieonderzoekbureaus'],
            ['SBI' => '741', 'Omschrijving' => 'Specialistische ontwerpactiviteiten'],
            ['SBI' => '742', 'Omschrijving' => 'Fotografie'],
            ['SBI' => '743', 'Omschrijving' => 'Vertalers tolken en overige specialistische dienstverlening'],
            ['SBI' => '749', 'Omschrijving' => 'Overige zakelijke dienstverlening rest'],
            ['SBI' => '751', 'Omschrijving' => 'Openbaar bestuur'],
            ['SBI' => '752', 'Omschrijving' => 'Rechtspraak en wetgeving'],
            ['SBI' => '753', 'Omschrijving' => 'Defensie'],
            ['SBI' => '754', 'Omschrijving' => 'Overheidsadministratie en overheidsdiensten'],
            ['SBI' => '755', 'Omschrijving' => 'Openbaar bestuur en overheidsdiensten'],
            ['SBI' => '771', 'Omschrijving' => 'Verhuur van auto\s en lichte bedrijfswagens'],
            ['SBI' => '772', 'Omschrijving' => 'Verhuur van overige consumentenartikelen'],
            ['SBI' => '773', 'Omschrijving' => 'Verhuur van overige machines en werktuigen en van overige goederen'],
            ['SBI' => '774', 'Omschrijving' => 'Leasing van niet-financiële goederen'],
            ['SBI' => '781', 'Omschrijving' => 'Uitzendbureaus'],
            ['SBI' => '782', 'Omschrijving' => 'Bemiddeling bij arbeidsmarktvraagstukken'],
            ['SBI' => '783', 'Omschrijving' => 'Overige arbeidsbemiddeling'],
            ['SBI' => '791', 'Omschrijving' => 'Reisorganisatie en reisbureaus'],
            ['SBI' => '799', 'Omschrijving' => 'Overige reisorganisatie'],
            ['SBI' => '801', 'Omschrijving' => 'Beveiliging'],
            ['SBI' => '802', 'Omschrijving' => 'Privédetective- en recherchebureaus'],
            ['SBI' => '803', 'Omschrijving' => 'Verkeerscontrole en beveiliging'],
            ['SBI' => '811', 'Omschrijving' => 'Dienstverlening voor gebouwen'],
            ['SBI' => '812', 'Omschrijving' => 'Schoonmaakbedrijven'],
            ['SBI' => '813', 'Omschrijving' => 'Landschapsverzorging'],
            ['SBI' => '821', 'Omschrijving' => 'Administratiekantoren'],
            ['SBI' => '822', 'Omschrijving' => 'Incassobureaus en kredietinformatie'],
            ['SBI' => '823', 'Omschrijving' => 'Markt- en opinieonderzoek'],
            ['SBI' => '829', 'Omschrijving' => 'Overige zakelijke dienstverlening'],
            ['SBI' => '841', 'Omschrijving' => 'Openbaar bestuur'],
            ['SBI' => '842', 'Omschrijving' => 'Internationale organisaties en extraterritoriale instituties'],
            ['SBI' => '851', 'Omschrijving' => 'Onderwijs'],
            ['SBI' => '852', 'Omschrijving' => 'Primair onderwijs'],
            ['SBI' => '853', 'Omschrijving' => 'Voortgezet onderwijs'],
            ['SBI' => '854', 'Omschrijving' => 'Middelbaar beroepsonderwijs'],
            ['SBI' => '855', 'Omschrijving' => 'Volwassenen- en ander onderwijs'],
            ['SBI' => '861', 'Omschrijving' => 'Ziekenhuizen'],
            ['SBI' => '862', 'Omschrijving' => 'Praktijken van medisch specialisten en verloskundigen'],
            ['SBI' => '863', 'Omschrijving' => 'Verpleging verzorging en thuiszorg'],
            ['SBI' => '871', 'Omschrijving' => 'Verzorgingshuizen'],
            ['SBI' => '872', 'Omschrijving' => 'Verpleeghuizen'],
            ['SBI' => '873', 'Omschrijving' => 'Geestelijke gezondheidszorg en verslavingszorg met overnachting'],
            ['SBI' => '879', 'Omschrijving' => 'Overige intramurale maatschappelijke dienstverlening n.e.g.'],
            ['SBI' => '881', 'Omschrijving' => 'Maatschappelijk werk voor ouderen en gehandicapten'],
            ['SBI' => '889', 'Omschrijving' => 'Overige maatschappelijke dienstverlening'],
            ['SBI' => '900', 'Omschrijving' => 'Creatieve kunstzinnige en culturele activiteiten'],
            ['SBI' => '910', 'Omschrijving' => 'Openbaar bestuur'],
            ['SBI' => '920', 'Omschrijving' => 'Gokken en wedden'],
            ['SBI' => '931', 'Omschrijving' => 'Sportactiviteiten'],
            ['SBI' => '932', 'Omschrijving' => 'Overige recreatie'],
            ['SBI' => '941', 'Omschrijving' => 'Activiteiten van ledengroepen en verenigingen'],
            ['SBI' => '949', 'Omschrijving' => 'Overige ledengroepen en verenigingen'],
            ['SBI' => '951', 'Omschrijving' => 'Reparatie van computers en consumentenartikelen'],
            ['SBI' => '952', 'Omschrijving' => 'Reparatie van huishoudelijke artikelen'],
            ['SBI' => '960', 'Omschrijving' => 'Overige persoonlijke dienstverlening'],
            ['SBI' => '970', 'Omschrijving' => 'Huishoudens als werkgever van huishoudelijk personeel'],
            ['SBI' => '981', 'Omschrijving' => 'Extraterritoriale organisaties en instellingen'],
            ['SBI' => '990', 'Omschrijving' => 'Internationale organisaties en organen']
        ];
        foreach ($sectors as $sector) {
            DB::table('sectors')->insert([
                'sbi_code' => $sector['SBI'],
                'name' => $sector['Omschrijving'],
            ]);
// Nu kun je deze array in je seeder gebruiken om de sectoren toe te voegen aan de database.
        }
    }
}

